[Desktop Entry]
Name=Instant Messaging
Name[ar]=التّراسل المباشر
Name[ast]=Mensaxería nel intre
Name[ca]=Missatgeria instantània
Name[cs]=Instant Messaging
Name[da]=Instant messaging
Name[de]=Instant-Messaging
Name[el]=Στιγμιαία μηνύματα
Name[en_GB]=Instant Messaging
Name[es]=Mensajería instantánea
Name[fi]=Pikaviestintä
Name[fr]=Messagerie instantanée
Name[gl]=Mensaxaría instantánea
Name[hu]=Azonnali üzenetküldés
Name[it]=Messaggistica istantanea
Name[ko]=인스턴트 메시징
Name[nb]=Lynmelding
Name[nl]=Instant Messaging
Name[nn]=Lydmeldingar
Name[pl]=Komunikator internetowy
Name[pt]=Mensagens Instantâneas
Name[pt_BR]=Mensagens instantâneas
Name[ro]=Mesagerie instantanee
Name[ru]=Мгновенные сообщения
Name[sk]=Priama komunikácia
Name[sl]=Hipno sporočanje
Name[sr]=Брзо гласништво
Name[sr@ijekavian]=Брзо гласништво
Name[sr@ijekavianlatin]=Brzo glasništvo
Name[sr@latin]=Brzo glasništvo
Name[sv]=Direktmeddelande
Name[tr]=Anında Mesajlaşma
Name[uk]=Миттєвий обмін повідомленнями
Name[x-test]=xxInstant Messagingxx
Name[zh_CN]=即时通讯
Name[zh_TW]=即時訊息
Comment=Displays your presence and contacts
Comment[ast]=Amuesa la to presencia y contautos
Comment[ca]=Mostra la vostra presència i els contactes
Comment[cs]=Zobrazuje vaši dostupnost a kontakty
Comment[da]=Viser din tilstedeværelse og kontakter
Comment[de]=Zeigt Ihre Anwesenheit und Kontakte
Comment[el]=Εμφανίζει τις επαφές και την παρουσία σας
Comment[en_GB]=Displays your presence and contacts
Comment[es]=Muestra su estado y sus contactos
Comment[fi]=Näyttää läsnäolon ja yhteystiedot
Comment[fr]=Affiche votre présence et vos contacts
Comment[gl]=Mostra a súa presenza e contactos.
Comment[hu]=Megjeleníti a jelenlétét és partnereit
Comment[it]=Mostra la tua presenza e i tuoi contatti
Comment[ko]=온라인 상태와 대화 상대 표시
Comment[nl]=Toont uw aanwezigheid en contactpersonen
Comment[nn]=Vis lynmeldingskontaktar
Comment[pl]=Wyświetla twoją dostępności i kontakty
Comment[pt]=Mostra a sua presença e contactos
Comment[pt_BR]=Mostra a sua presença e contatos
Comment[ro]=Vă afișează prezența și contactele
Comment[ru]=Показывает список контактов и ваш статус
Comment[sk]=Zobrazí vašu prítomnosť a kontakty
Comment[sl]=Prikaže vašo prisotnost in stike
Comment[sr]=Приказ вашег присуства и контаката
Comment[sr@ijekavian]=Приказ вашег присуства и контаката
Comment[sr@ijekavianlatin]=Prikaz vašeg prisustva i kontakata
Comment[sr@latin]=Prikaz vašeg prisustva i kontakata
Comment[sv]=Visar din närvaro och kontakter
Comment[tr]=Kimliğini ve bağlantılarını görüntüler
Comment[uk]=Показувати дані щодо вашої присутності та контактів
Comment[x-test]=xxDisplays your presence and contactsxx
Comment[zh_CN]=显示您的状态和联系人
Comment[zh_TW]=顯示您的上線狀態與聯絡人
Type=Service
ServiceTypes=Plasma/Applet
Icon=meeting-attending

X-Plasma-API=declarativeappletscript
X-Plasma-MainScript=ui/main.qml
X-Plasma-DefaultSize=200,300
X-Plasma-NotificationArea=true
X-Plasma-NotificationAreaCategory=Communications
X-Plasma-DBusActivationService=org.freedesktop.Telepathy.MissionControl5

X-KDE-PluginInfo-Name=org.kde.ktp-contactlist
X-KDE-PluginInfo-Category=Online Services
X-KDE-PluginInfo-Author=David Edmundson
X-KDE-PluginInfo-Email=kde@davidedmundson.co.uk
X-KDE-PluginInfo-Version=@KTP_DESKTOP_APPLETS_VERSION@
X-KDE-PluginInfo-Website=http://telepathy.freedesktop.org/

X-KDE-PluginInfo-Depends=
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=true
X-KDE-ServiceTypes=Plasma/Applet,Plasma/PopupApplet
Type=Service
