[Desktop Entry]
Name=Instant Messaging
Name[cs]=Instant Messaging
Name[de]=Instant-Messaging
Name[fi]=Pikaviestintä
Name[nl]=Instant Messaging
Name[pl]=Komunikator internetowy
Name[pt]=Mensagens Instantâneas
Name[pt_BR]=Mensagens instantâneas
Name[sk]=Priama komunikácia
Name[sr]=Брзо гласништво
Name[sr@ijekavian]=Брзо гласништво
Name[sr@ijekavianlatin]=Brzo glasništvo
Name[sr@latin]=Brzo glasništvo
Name[uk]=Миттєвий обмін повідомленнями
Name[x-test]=xxInstant Messagingxx
Comment=Displays your presence and contacts
Comment[cs]=Zobrazuje vaši dostupnost a kontakty
Comment[de]=Zeigt Ihre Anwesenheit und Kontakte
Comment[fi]=Näyttää läsnäolon ja yhteystiedot
Comment[nl]=Toont uw aanwezigheid en contactpersonen
Comment[pl]=Wyświetla twoją dostępności i kontakty
Comment[pt]=Mostra a sua presença e contactos
Comment[pt_BR]=Mostra a sua presença e contatos
Comment[sk]=Zobrazí vašu prítomnosť a kontakty
Comment[sr]=Приказ вашег присуства и контаката
Comment[sr@ijekavian]=Приказ вашег присуства и контаката
Comment[sr@ijekavianlatin]=Prikaz vašeg prisustva i kontakata
Comment[sr@latin]=Prikaz vašeg prisustva i kontakata
Comment[uk]=Показувати дані щодо вашої присутності та контактів
Comment[x-test]=xxDisplays your presence and contactsxx
Type=Service
ServiceTypes=Plasma/Applet
Icon=meeting-attending

X-Plasma-API=declarativeappletscript
X-Plasma-MainScript=ui/main.qml
X-Plasma-DefaultSize=200,300
X-Plasma-NotificationArea=true
X-Plasma-DBusActivationService=org.freedesktop.Telepathy.MissionControl5

X-KDE-PluginInfo-Name=org.kde.ktp-contactlist
X-KDE-PluginInfo-Category=Online Services
X-KDE-PluginInfo-Author=David Edmundson
X-KDE-PluginInfo-Email=kde@davidedmundson.co.uk
X-KDE-PluginInfo-Version=@KTP_DESKTOP_APPLETS_VERSION@
X-KDE-PluginInfo-Website=http://telepathy.freedesktop.org/

X-KDE-PluginInfo-Depends=
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=true
X-KDE-ServiceTypes=Plasma/Applet,Plasma/PopupApplet
Type=Service
